version: '3.5'
networks:
  selenoid:
    external:
      name: selenoid
services:
  jenkins:
    user: root
    restart: unless-stopped
    build:
      context: ./image
    volumes:
      - ${PWD}/work/jenkins:/var/jenkins_home
      - /ver/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    networks:
      - selenoid
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    ports:
      - 4444:4444
    volumes:
      - "${PWD}/init/selenoid:/etc/selenoid"
      - "${PWD}/work/selenoid/video:/opt/selenoid/video"
      - "${PWD}/work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/work/selenoid/video
    command:  ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    networks:
      - selenoid
    expose:
      - "80"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    networks:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  
